# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Garbanzo < Formula
  desc "notification viewer"
  homepage "https://github.com/kijimaD/garbanzo"
  version "0.2.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kijimaD/garbanzo/releases/download/v0.2.7/garbanzo_Darwin_x86_64.tar.gz"
      sha256 "74372cdc292fe0b7ace2ac7ad468ba3925249e93773ff6fc33fef3281c9f3248"

      def install
        bin.install "garbanzo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kijimaD/garbanzo/releases/download/v0.2.7/garbanzo_Darwin_arm64.tar.gz"
      sha256 "e461181e0328f6b24eaeaae8c916ed1c3b268f333f1f935e2d9f7f95b6542a01"

      def install
        bin.install "garbanzo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kijimaD/garbanzo/releases/download/v0.2.7/garbanzo_Linux_arm64.tar.gz"
      sha256 "cd443c3b0d50cd9b02d7063845b8d674e013df502b54b45c3c000653c6eaf216"

      def install
        bin.install "garbanzo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kijimaD/garbanzo/releases/download/v0.2.7/garbanzo_Linux_x86_64.tar.gz"
      sha256 "60c25e4709314f0529560aa790bc68e655f7d64f3691216153be29fc95b5699f"

      def install
        bin.install "garbanzo"
      end
    end
  end
end
