# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Silver < Formula
  desc "reproduce the system"
  homepage "https://github.com/kijimaD/silver"
  version "1.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kijimaD/silver/releases/download/v1.5.0/silver_Darwin_x86_64.tar.gz"
      sha256 "c5b0065384e9a464dac6e90a605ff5e01710476f04321822fe4801db4ccd4ab4"

      def install
        bin.install "silver"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kijimaD/silver/releases/download/v1.5.0/silver_Darwin_arm64.tar.gz"
      sha256 "80769f7abd013e39c80923c645edee07c34c8e6575a6eebcf7237d5c0f940977"

      def install
        bin.install "silver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kijimaD/silver/releases/download/v1.5.0/silver_Linux_arm64.tar.gz"
      sha256 "8b3d71dd86c45cf5931640155da26d820de8cbbddcee796e78b9f938d6b9408e"

      def install
        bin.install "silver"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kijimaD/silver/releases/download/v1.5.0/silver_Linux_x86_64.tar.gz"
      sha256 "f83329f79e78859215348c0a799414ba397c0b9cb71b59260fe68f56c95275ae"

      def install
        bin.install "silver"
      end
    end
  end
end
