# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Upl < Formula
  desc "upload zip file to Tiny File Manager by CLI"
  homepage "https://github.com/kijimaD/upl"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kijimaD/upl/releases/download/v0.1.3/upl_Darwin_x86_64.tar.gz"
      sha256 "5b9d4d7765e19e2ab27ecf656a9e4188f13192d47d3f521ef7f566712eb3c0e1"

      def install
        bin.install "upl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kijimaD/upl/releases/download/v0.1.3/upl_Darwin_arm64.tar.gz"
      sha256 "7293f0b906a3302d7c97549cb72e30d4f660b42b2e0f31af69c361c46335817a"

      def install
        bin.install "upl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kijimaD/upl/releases/download/v0.1.3/upl_Linux_arm64.tar.gz"
      sha256 "3d13e92613513bd28356deaf3a7649abe94fcb6bf9bed44edd38d82161ce20b2"

      def install
        bin.install "upl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kijimaD/upl/releases/download/v0.1.3/upl_Linux_x86_64.tar.gz"
      sha256 "6e74d78a6dd0b66738e088401da1c3b7a611eeb870f588f2a3568da24a4bed28"

      def install
        bin.install "upl"
      end
    end
  end
end
