# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Upl < Formula
  desc "upload zip file to Tiny File Manager by CLI"
  homepage "https://github.com/kijimaD/upl"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kijimaD/upl/releases/download/v0.1.1/upl_Darwin_arm64.tar.gz"
      sha256 "02b921c110b89293866058c1b88511d8b8ca6bfde355b7886da8f3a68ad58544"

      def install
        bin.install "upl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kijimaD/upl/releases/download/v0.1.1/upl_Darwin_x86_64.tar.gz"
      sha256 "4735bca0575a94fe93d1e4d64d3a3f89d30ef41a78528e87622c39ac727d3ee3"

      def install
        bin.install "upl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kijimaD/upl/releases/download/v0.1.1/upl_Linux_arm64.tar.gz"
      sha256 "2276a9f8d293ceb3aa7f8a1a383a8f85353d019e6e5a8bfa648bd110a0778e97"

      def install
        bin.install "upl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kijimaD/upl/releases/download/v0.1.1/upl_Linux_x86_64.tar.gz"
      sha256 "bb64a307da4fa3fb08fe721bf4bb6e6971473a85acf10c67c079ad4a86aafc92"

      def install
        bin.install "upl"
      end
    end
  end
end
