# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Garbanzo < Formula
  desc "notification viewer"
  homepage "https://github.com/kijimaD/garbanzo"
  version "0.2.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kijimaD/garbanzo/releases/download/v0.2.6/garbanzo_Darwin_x86_64.tar.gz"
      sha256 "5b6b1ef2611a47f4399b3b2145caf9966e912faab9aef73e143e2ede9f0570a8"

      def install
        bin.install "garbanzo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kijimaD/garbanzo/releases/download/v0.2.6/garbanzo_Darwin_arm64.tar.gz"
      sha256 "5ae445bdb51e4854c3b5b4a2e7826f52497de65894a84dc5b69851b70581aa23"

      def install
        bin.install "garbanzo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kijimaD/garbanzo/releases/download/v0.2.6/garbanzo_Linux_arm64.tar.gz"
      sha256 "d16c0eeb27600928c71ed01227344e82b13abd55a529fe823d70b823d66fe51d"

      def install
        bin.install "garbanzo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kijimaD/garbanzo/releases/download/v0.2.6/garbanzo_Linux_x86_64.tar.gz"
      sha256 "fd32c52f74cdee62debb5d7e308b1b7b7c691e81c0d3ce539f2afcf475622d6b"

      def install
        bin.install "garbanzo"
      end
    end
  end
end
